### ISSUE TITLE
Wiring pi wont compile

### ISSUE THREAD

**Issue by beniroquai** [tjanson/PiSwitch#4]
When I do "npm install wiringpi", after a while I get this output:

/home/pi/.node-gyp/0.12.0/deps/v8/include/v8.h:3455:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
/home/pi/.node-gyp/0.12.0/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
wiringPi.target.mk:85: recipe for target 'Release/obj.target/wiringPi/src/bindings.o' failed
make: *** [Release/obj.target/wiringPi/src/bindings.o] Error 1
make: Leaving directory '/home/pi/heimcontrol.js/node_modules/piswitch/node_modules/wiring-pi/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.12.35+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/heimcontrol.js/node_modules/piswitch/node_modules/wiring-pi
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Linux 3.12.35+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "piswitch"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! wiring-pi@1.1.2 install: `/bin/bash ./install.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wiring-pi@1.1.2 install script '/bin/bash ./install.sh'.
npm ERR! This is most likely a problem with the wiring-pi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     /bin/bash ./install.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls wiring-pi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/heimcontrol.js/npm-debug.log

Im using wheezy and wanted to install heimcontrol.js. Any idea what could be wrong? thank you!

**Comment by tjanson** [comment]
I’ve updated the `wiring-pi` dependency to use version 2.0.0 in the hope that that’ll fix it. It should work, but I haven’t tested it at all. (I don’t have a Pi ready for testing right now, nor much time.)

If you try it, please report back either way. :)

**Comment by nekuz0r** [comment]
The problem is wiring-pi 2.0.0 is not ready for node 0.12.x, wiring-pi 2.1.0 will be released in the next weeks with support for node 0.12.x, raspberry pi A+ and raspberry pi 2.

**Comment by joeking11829** [comment]
Cool !
I have same problem, i will downgrade my Node.js.
And try to install again.

**Comment by dirkels** [comment]
Had similar problems and after downgrading to node v0.10.36 it all worked fine (https://node-arm.herokuapp.com/node_0.10.36_armhf.deb). Well apart from Raspberry Pi 2 not being supported yet but that is in the works I read.

**Comment by ghost** [comment]
For NodeJS 0.12.x :

Before installing piSwitch (if already installed, remove it)
Install this version of WiringPi : npm install git+https://git@github.com/nekuz0r/wiring-pi.git#incoming-node-v0.12.x
(https://github.com/eugeneware/wiring-pi/pull/20#issuecomment-76250149)
Install piSwitch npm install piSwitch

And now...it works fine on NodeJS 0.12.x

**Comment by R1CH-T** [comment]
Hi Tom,
Is it still, currently the case that you have to install a different version of WiringPi, as above ^ ?
I still can't get the darned thing to work.
Thanks,
Rich.

**Comment by tjanson** [comment]
@R1CH-T: I’m not sure, I haven’t used PiSwitch in a while. I might get to it this weekend or next – I’ve been meaning to set up it up again in my new appartment, but haven’t had the time.

**Comment by R1CH-T** [comment]
Thanks, Tom. :)
